import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useState, useEffect } from 'react';
import { findAll } from '../service/attachments';

const Home: NextPage = () => {
  useEffect(() => {
    findAll(12);
  }, []);
  return (
    <div className={styles.container}>
      <h1>
        <title>This is a GRPC client App. 
          Please launch browser console to see grpc server response</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </h1>
    </div>
  )
}

export default Home
